### ISSUE TITLE
Strip down 1.0.0-M1 by simplifying authentication and removing click and visitor tracking

### ISSUE THREAD

**Issue by laszlocsontos** [laszlocsontos/relinkr#55]
- [x] Remove Facebook authentication
- [x] Refactor so that User ID be longer than 64 bits
- [x] Remove user profile handling
- [x] Remove click tracking
- [x] Remove visitor tracking
